# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crosswalk < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/crosswalk"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/crosswalk/releases/download/v0.6.0/crosswalk_Darwin_x86_64.tar.gz"
      sha256 "6459af2421db1c9a3d7e12508a575a6e61f6bf768d7a67992620fb59ab25897d"

      define_method(:install) do
        bin.install "crosswalk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/crosswalk/releases/download/v0.6.0/crosswalk_Darwin_arm64.tar.gz"
      sha256 "425bbc5dbb0cdd072e447440b58ce5c3e8abaa01c57d5241713b50656515966e"

      define_method(:install) do
        bin.install "crosswalk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/crosswalk/releases/download/v0.6.0/crosswalk_Linux_x86_64.tar.gz"
      sha256 "3c6e3707189d65b06e07a6f70602c1711b7a9016a90c04fc49e2963e7f5e4c1e"
      define_method(:install) do
        bin.install "crosswalk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/crosswalk/releases/download/v0.6.0/crosswalk_Linux_arm64.tar.gz"
      sha256 "d2b6bee8eb72513b85c7816b1f169de1e6ad64e665f06a1f444435c25a337096"
      define_method(:install) do
        bin.install "crosswalk"
      end
    end
  end
end
