# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerAutoheal < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/docker-autoheal"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/docker-autoheal/releases/download/0.2.2/docker-autoheal_Darwin_x86_64.tar.gz"
      sha256 "12a71d2ead6106d47fa4fdee7336012557b3450b6f0c51c945d29fa28c92fef3"

      def install
        bin.install "docker-autoheal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/docker-autoheal/releases/download/0.2.2/docker-autoheal_Darwin_arm64.tar.gz"
      sha256 "30484cc7444a1c76c7d5e187b8d0f016ae894c0bb3a118a74e7f1b6d83f9f19b"

      def install
        bin.install "docker-autoheal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lehigh-university-libraries/docker-autoheal/releases/download/0.2.2/docker-autoheal_Linux_x86_64.tar.gz"
        sha256 "dc5bc3fb4b3d80d869d1960d294103b24d7be737ce89423bdc8a5f1b6574d7b4"

        def install
          bin.install "docker-autoheal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lehigh-university-libraries/docker-autoheal/releases/download/0.2.2/docker-autoheal_Linux_arm64.tar.gz"
        sha256 "50b79d6eef4ae6bce08221ca3fbc30ac2517fcec159a4fd466c09c1501bbe152"

        def install
          bin.install "docker-autoheal"
        end
      end
    end
  end
end
