# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Encode < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/encode"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.4.1/encode_Darwin_x86_64.tar.gz"
      sha256 "b22e980f0d21feff581f9d590ecae12ce377e9c3a1cb9d7c65a2d6a0b4940859"

      def install
        bin.install "encode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.4.1/encode_Darwin_arm64.tar.gz"
      sha256 "9294fc1505515a382b803119cae00b80f9f24bd538697b9b35f85161624b1c0b"

      def install
        bin.install "encode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.4.1/encode_Linux_x86_64.tar.gz"
      sha256 "af29d82f8e370acc9b6b9f7f747d7106cc55705be69ddea864397b5c20e370e2"
      def install
        bin.install "encode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.4.1/encode_Linux_arm64.tar.gz"
      sha256 "2ca3aa4a9673fb50b7f93298813bd2a98cef9bdc6166352681c843f1b4e21b1a"
      def install
        bin.install "encode"
      end
    end
  end
end
