# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Encode < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/encode"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.0.0/encode_Darwin_x86_64.tar.gz"
      sha256 "6729561d3549e73a47ac849f76faa18bc715d4ab639721fabb6650237e74ba3e"

      def install
        bin.install "encode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.0.0/encode_Darwin_arm64.tar.gz"
      sha256 "7e159d4340bbb288952617832ce9f7be9741d11a8aabf4be91bd8cd3288d5075"

      def install
        bin.install "encode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.0.0/encode_Linux_x86_64.tar.gz"
      sha256 "c2c6a7b5e6bd25805c34aefa5e836e4e981c2136f3eeffa6937330a3248a417b"
      def install
        bin.install "encode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/encode/releases/download/0.0.0/encode_Linux_arm64.tar.gz"
      sha256 "2abf05213318a15e98129060ca01365d3fbdd3655a0ca3e428644d7c3ed8c7d5"
      def install
        bin.install "encode"
      end
    end
  end
end
