# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hawkeye < Formula
  desc "Flag PDF and image pages for sensitive-information review"
  homepage "https://github.com/lehigh-university-libraries/hawkeye"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.1.0/hawkeye_Darwin_x86_64.tar.gz"
      sha256 "6e531721aee26248c0b6476e94a209eceb1e43ea35f7bdf35ed0768f2ba94739"

      define_method(:install) do
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.1.0/hawkeye_Darwin_arm64.tar.gz"
      sha256 "d3b97e525479522bf3b34e3a472422cb0f466c0100fd20da8a7e552ccff818c0"

      define_method(:install) do
        bin.install "hawkeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.1.0/hawkeye_Linux_x86_64.tar.gz"
      sha256 "0ed28ba633a21367a154a9e897c21c54c6c3de156f1dac9df36e5311cbd4c3d6"
      define_method(:install) do
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.1.0/hawkeye_Linux_arm64.tar.gz"
      sha256 "7465d1346478ecc90e7c69819e1b425bc256e976e4ebfaa3108161adec33b538"
      define_method(:install) do
        bin.install "hawkeye"
      end
    end
  end

  def caveats
    <<~EOS
      A running Docker daemon and access to an on-prem Ollama service are required.
      Set OLLAMA_URL to override the default Lehigh Ollama endpoint.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hawkeye --version")
  end
end
