# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hawkeye < Formula
  desc "Flag PDF and image pages for sensitive-information review"
  homepage "https://github.com/lehigh-university-libraries/hawkeye"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.1/hawkeye_Darwin_x86_64.tar.gz"
      sha256 "fa07917a2d47e615aaca5842768cf13c54243026a8cd44d12828440776bbf836"

      define_method(:install) do
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.1/hawkeye_Darwin_arm64.tar.gz"
      sha256 "e4a14daa2be3fe34dfeb2e9f569601fcb39f49be804ef498d82a90c6649f62a1"

      define_method(:install) do
        bin.install "hawkeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.1/hawkeye_Linux_x86_64.tar.gz"
      sha256 "1b0ec833d4c1c748faa744ed6e37e4a29ea32a11f3913c339a1e3d9272c84645"
      define_method(:install) do
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.1/hawkeye_Linux_arm64.tar.gz"
      sha256 "be8e59767db308dc4a24b6741c4c9f4f29c5d3839dc5758bab37e90bfd534265"
      define_method(:install) do
        bin.install "hawkeye"
      end
    end
  end

  def caveats
    <<~EOS
      A running Docker daemon and access to an on-prem Ollama service are required.
      Set OLLAMA_URL to override the default Lehigh Ollama endpoint.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hawkeye --version")
  end
end
