# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hawkeye < Formula
  desc "Flag PDF and image pages for sensitive-information review"
  homepage "https://github.com/lehigh-university-libraries/hawkeye"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.2/hawkeye_Darwin_x86_64.tar.gz"
      sha256 "89eb9d75757d7583b7580adc513ae8110f248306f4cbb76f5ff4f20bf172f5be"

      define_method(:install) do
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.2/hawkeye_Darwin_arm64.tar.gz"
      sha256 "578760e22679e4960bdfa875450c1dc54b88b22560c7485f93898b202e777da8"

      define_method(:install) do
        bin.install "hawkeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.2/hawkeye_Linux_x86_64.tar.gz"
      sha256 "298abb5064bf4bc57482928c84026778370e05f6232bb6833732a4356f257d91"
      define_method(:install) do
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/hawkeye/releases/download/v0.0.2/hawkeye_Linux_arm64.tar.gz"
      sha256 "6f0221522c1b46e98abb5e39c827b437da05cc93fc9ab957586a08c7e5ff7364"
      define_method(:install) do
        bin.install "hawkeye"
      end
    end
  end

  def caveats
    <<~EOS
      A running Docker daemon and access to an on-prem Ollama service are required.
      Set OLLAMA_URL to override the default Lehigh Ollama endpoint.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hawkeye --version")
  end
end
