# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Htr < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/htr"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.2.0/htr_Darwin_x86_64.tar.gz"
      sha256 "ea02225835df486a12dd7729b93df379f35d86cb360ad027e949ccc2787f57a0"

      def install
        bin.install "htr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.2.0/htr_Darwin_arm64.tar.gz"
      sha256 "1ee91eec144466c52f032b320610079172754feb52cadebc95dc16a8d14c588b"

      def install
        bin.install "htr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.2.0/htr_Linux_x86_64.tar.gz"
      sha256 "2d1ce9432686eab7f7e5aa7f9a70a650596410b89af73dbe8fb5710a1af91f82"
      def install
        bin.install "htr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.2.0/htr_Linux_arm64.tar.gz"
      sha256 "86ffb65dffa05c0c2d79e841d890bc9281dde6f19cc96a15eb02bd402b40b866"
      def install
        bin.install "htr"
      end
    end
  end
end
