# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Htr < Formula
  desc ""
  homepage "https://github.com/lehigh-university-libraries/htr"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.0.1/htr_Darwin_x86_64.tar.gz"
      sha256 "e4dd7473cd8e648f16cd14b19b6bc464a4005064e3aa9012a54589ec426d9eef"

      def install
        bin.install "htr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.0.1/htr_Darwin_arm64.tar.gz"
      sha256 "6bb8a1a120fb6596678259cde1898b7999d4f02f78aba9a718f4b23e32dc92d1"

      def install
        bin.install "htr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.0.1/htr_Linux_x86_64.tar.gz"
      sha256 "521381d59ae300ef16fec394d46dd2943c288ab60246fd9fbf951ad85ebab738"
      def install
        bin.install "htr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lehigh-university-libraries/htr/releases/download/0.0.1/htr_Linux_arm64.tar.gz"
      sha256 "af9c48388d8242319a0aab04bbe82599341e2cc142771d2d2190fd8aa045522b"
      def install
        bin.install "htr"
      end
    end
  end
end
