# This file was generated by GoReleaser. DO NOT EDIT.
cask "scribe" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "69d8f0f572aaa82966f5bf4ce0248ef0084064aebbf3c9c0e61fdb1cc78d268f"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "350c07f3eb5a17a8d6a70915fb173b783e61e1079ac2faafaf33106fd6d11e7e"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a639d3c262790cf2cf9a12915be4181772000d0b0659b3534e4359649f4d073"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2913f1a5436f1a53cc7a3418311702d4662023076e16bcee4a506d8b3f82d288"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Linux_arm64.tar.gz"
    end
  end

  name "scribe"
  desc "IIIF-native handwritten document segmentation, transcription, and correction services"
  homepage "https://github.com/lehigh-university-libraries/scribe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scribe-api"
  binary "scribe-worker"

  # No zap stanza required

end
