# This file was generated by GoReleaser. DO NOT EDIT.
cask "scribe" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "2ea685924f08ad03382a66996c287310348357b2b7c39788cd93cad4d8109f08"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9b42cd67444a43a3dd7a084f36e05368a6d9a284c04e10ad40918188be89d9cd"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fc46a50d3753c783ddb5701531939cf58cfa7654bb64e1371f179e859c39561"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e158a9f1b2a1722d5bd3ad5b5060661fb295cb0583db408b7b76bddf13c5c38f"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Linux_arm64.tar.gz"
    end
  end

  name "scribe"
  desc "IIIF-native handwritten document segmentation, transcription, and correction services"
  homepage "https://github.com/lehigh-university-libraries/scribe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scribe-api"
  binary "scribe-worker"

  # No zap stanza required

end
