# This file was generated by GoReleaser. DO NOT EDIT.
cask "scribe" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "f0ac485d63b34572acb2c58f3ef8f80e9eee0909fc04a32c0a06ce19d5e45945"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "14283830bf8c4ba37a068c5eac0c1c23b081eaef8e0898001b852188e4a3fbfc"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7123908bd61198068c6082dd7cbe3cc48048b371af5b7dcfc8d0d4f6285a6f69"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "75890d7e829407c25ca64b4c8b57dc8a8aba24e6e463c4a17d3957d91519d060"
      url "https://github.com/lehigh-university-libraries/scribe/releases/download/#{version}/scribe_Linux_arm64.tar.gz"
    end
  end

  name "scribe"
  desc "IIIF-native handwritten document segmentation, transcription, and correction services"
  homepage "https://github.com/lehigh-university-libraries/scribe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scribe-api"
  binary "scribe-worker"

  # No zap stanza required

end
